### PR TITLE
Minor changes, update deps

### PR DESCRIPTION
**Pull request by 19h**
- fixes AAPL test case
- updates dependencies excluding tungstenite
- changes an log call which failed to format the passed variable, therefore I changed the formatter (display(&msg) -> %msg)

### CODE REVIEW

**Comment by 19h** [comment]
Needed the formatting change to be able to build polycli:

CleanShot 2020-08-03 at 01 02 43@2x

**Comment by d-e-s-o** [comment]
Thanks for the pull request!

> * fixes AAPL test case

So here the issue is that I believe for some reason `polygon.io` reports one thing at times and another at others. I recall changing that and then it just broke again. If I recall correctly, I suspected a connection between open & closed markets (one string is returned when open, the other when closed; but I have not yet verified that). It's utterly stupid. We need to work with upstream to get this fixed. First step would be to verify the market open/close hypothesis tomorrow. I may be able to have a quick look tomorrow, but feel free to have a look as well if you are interested in driving this forward.

> * changes an log call which failed to format the passed variable, therefore I changed the formatter (display(&msg) -> %msg)

This is actually an issue on the `tracing` side. Please see https://github.com/tokio-rs/tracing/issues/874, which I reported yesterday. I hope they get to that. I am super unhappy with their stuff. It's the third build breakage they got me into. Every single time it's their crate. In fact, `tracing` is the one single source of build breakages in all my shit. Unfortunately, it's the only option I see.
I'd rather not modify my code at this point, because the intention really is to use the `Display` representation. Let's table that for now for a few more days. This actually works if you pin `h2`/`hyper` to a certain version (I believe `hyper = '=0.13.5'`). I suggest you keep that locally for now, then let's see if `tracing` folks fix their s***. Usually the maintainer is accommodating, but I am not super hopeful on this one.

> * updates dependencies excluding tungstenite

I don't think we need to bump the patch versions of crates. Everything should work with earlier versions and so I prefer to keep the specification at the minor version level. I'd also like to keep whitespace changes to a minimum. I use the same style in all my crates, so this would just create an odd one out.
I am happy to take the `websocket-util` (I had that locally but never pushed), `tungstenite` & `tracing-subscriber` bumps. Would you mind creating a separate patch for that? If you do, please also add an entry to `CHANGELOG.md`. Thanks!

**Comment by d-e-s-o** [comment]
FYI, build failure got fixed now. Remove your `Cargo.lock` and rebuild.

**Comment by d-e-s-o** [comment]
Committed the remaining two changes in slightly modified form. Thanks again.

**Pull request closed without merging**
