### PR TITLE
Migrate to Rust 2021

### PR DESCRIPTION
**Pull request by 19h**
Currently polyio doesn't build in projects using the 2021 resolver as many default features are not selected anymore by default in the Rust 2021 edition.

Reference: https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html#migration

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Thanks for the pull request. I am not sure I understand why we need edition 2021 and not just the addition of this one feature. Do you have an explanation? Also, do you have a reproduction, by any chance?

**Comment by 19h** [comment]
Create a new project using `cargo new foo`, cd into the folder, `cargo add polyio`, `cargo build`.

If you’re running the latest Rust it’ll throw compiler errors.

**Comment by 19h** [comment]
CleanShot 2022-03-07 at 15 21 46@2x

**Comment by 19h** [comment]
I see the point of simply adding the feature in question -- but given that future projects will be initialised into using the 2021 edition I don't understand why you'd insist on sticking to it given that even already you couldn't possibly have noticed the incompatibility with 2021 edition projects. I feel that this would simply lead to unintentional breakage down the line for no good reason.

**Comment by d-e-s-o** [comment]
Thanks! Edition 2021 requires Rust `1.56`. We still support `1.54` at this point, so bumping would be a backwards compatibility breaking change. We can just use resolver `2`, which stabilized earlier.

```diff
--- Cargo.toml
+++ Cargo.toml
@@ -19,9 +19,10 @@ description = """
 A create for interacting with the Polygon API at polygon.io.
 """
 include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
+resolver = "2"

 [dependencies]
-chrono = {version = "0.4", default-features = false, features = ["serde"]}
+chrono = {version = "0.4", default-features = false, features = ["serde", "std"]}
 futures = {version = "0.3", default-features = false}
 http = {version = "0.2", default-features = false}
 http-endpoint = "0.5"
```

**Comment by d-e-s-o** [comment]
I've adjusted the patch accordingly and merged it. Thanks for pointing this issue out!

**Pull request closed without merging**
